# Generated by Django 5.0.2 on 2025-05-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_add_default_categories'),
        ('books', '0003_review'),
    ]

    operations = [
    ]
